aerospikeConfiguration:
  hosts:
    -
      ip: "localhost"
      port: 3000
  username: ""
  password: ""
  namespace: "test"
  set: "pmu_frames_rt"
  truncateSet: False
  tlsPath: ""
outputWindowConfiguration:
  printIntervalSec: 1
  numberOfLinesBeforeReprintingTheHeader: 25
  columnWidth: 11
testConfiguration:
  perseusId: 0
  pmuStreamCount: 10
  pmuStreamStartIndex: 1
  pmuStreamPrefix: "pdc"
  pmuComplexCount: 137
  pmuRealCount: 144
  pmuFps: 200
  pmuTtlSeconds: 43200
  c37118ReceiverHost: "localhost"
  c37118ReceiverPort: 4712
  bookingSet: "bookings"
  bookingPassengerCount: 200000
  bookingFlightCount: 5000
  bookingSeededCount: 300000
  bookingCounterBatch: 100
